server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**

        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket/**

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER_URL:http://localhost:8500}/eureka/

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"