server:
  port: 8501

spring:
  application:
    name: account-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}

management:
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spcloud:
  cassandra:
    contact:
      point: localhost
    port : 9042
    keyspace:
      name: springcloud

    username : cassandra
    password : cassandra

resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold : 90