server:
  port: ${SERVER_PORT:8501}

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

spring:
  application:
    name: account-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}

management:
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

spcloud:
  cassandra:
    contact:
      point: ${CASSANDRA_SERVER_HOST:localhost}
    port : ${CASSANDRA_SERVER_PORT:9042}
    keyspace:
      name: ${CASSANDRA_SERVER_KEYSPACE:springcloud}

    username : ${CASSANDRA_SERVER_USERNAME:cassandra}
    password : ${CASSANDRA_SERVER_PASSWORD:cassandra}

resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold : 90