server:
  port: ${SERVER_PORT:8503}

spring:
  application:
    name: notification-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
  rabbitmq:
    listener:
      simple:
        message-converter:
          jackson:
            trusted-packages: "*"
    username: uur
    password: uur
    boot:
      admin:
        client:
          url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

msrabbitmq:
  exchange: default
  queue: msqueue
  routingKey: firstRoute

management:
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}