server:
  port: ${SERVER_PORT:8502}

spring:
  application:
    name: ticket-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/microserviceroot?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:microservice-root}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: ${RABBITMQ_USERNAME:uur}
    password: ${RABBITMQ_PASSWORD:uur}
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

msrabbitmq:
  exchange: default
  queue: msqueue
  routingKey: firstRoute

management:
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold : 90