server:
  port: 8502

spring:
  application:
    name: ticket-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceroot?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: microservice-root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: uur
    password: uur
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
msrabbitmq:
  exchange: default
  queue: msqueue
  routingKey: firstRoute

management:
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold : 90